### ISSUE TITLE
Pdp Json contract

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise#150]
Regarding the suggestions on the pdp page:

For the quick view feature @JulianSamarjiev needs the json to contain a full view of the product (with sizes, colors  etc) while for the initial page view only thumbnail data is needed (name, desc., price, image). The contract used to be, that only thumbnail data is provided and so does the model. I can change it, but i think it might make more sense to load the full product separately. 

@lauraluiz you already made this decision for maximilian or sth.?
@trangng  can we discus it and have a final decision here

**Comment by nkuehn** [comment]
@JulianSamarjiev @peter-gerhard  does anything speak against allowing the view model to contain more properties than the contract with the template has defined?  That could allow more re-use and less dumb duplicate view model work in the backend. 

it would be extremely helpful, esp. in the dynamic languages like PHP and node because then it would be enough to just add the stuff that's not 1:1 the API instead of having to build complete model objects in full depth from zero just because one of 50 properties differs from the API.

**Comment by peter-gerhard** [comment]
@nkuehn there is nothing against it.

**Comment by butenkor** [comment]
Nothing against it if view is rendered server side. If it is rendered client side (ajax) then you have to filter out customer related prices from variants server side. It should not be possible to view for customer group A the prices of customer group B.

**Comment by nkuehn** [comment]
@butenkor +1 that's right. To be able to do client-side ajax updates the view model must be a whitelist.

**Comment by lauraluiz** [comment]
It depends on the value resolver you use/implement, so technically all possibilities are unlimited. But as @butenkor said, it is quite difficult to reuse the API JSON without some manipulation, but at least maybe you can save some models, of course.

**Comment by lauraluiz** [comment]
All the JSON contract was already adapted as needed
