### ISSUE TITLE
Static texts to show for delivery and returns

### ISSUE THREAD

**Issue by peter-gerhard** [sphereio/sphere-sunrise#168]
@trangng 
As agreed, please provide static text to show as information for delivery & returns and decide if we split the accordion in two or not.

**Comment by trangng** [comment]
@peter-gerhard 

I would not split the accordion

Here is the text in DE:

Standardversand - 3 € oder KOSTENLOS ab einem Bestellwert von 29,99 €. 
Lieferung innerhalb von 4 Werktagen. 

Expressversand - 6 €. Lieferung innerhalb von 2 Werktagen.  

Kostenlose Rücksendung bei allen Bestellungen.

Mehr Infos hier › (link to FAQ static page, which does not exist yet)

Standard delivery - FREE for orders over €29.99, otherwise €3.00. Delivery within 4 working days

Express delivery - €6.00. Delivery within 2 working days

Free return for all orders.

More info > (link to FAQ Delivery & returns)
