### ISSUE TITLE
Which locales do we support?

### ISSUE THREAD

**Issue by schleichardt** [sphereio/sphere-sunrise#18]
I think we should at least support German and English. @lauraluiz

**Comment by lauraluiz** [comment]
This information will be directly provided by the project endpoint, so it depends on the data.

**Comment by schleichardt** [comment]
Sorry for reopening, but what is about the languages we put into the play i18n files?

**Comment by lauraluiz** [comment]
True that, but that would depend on the template. What we have to achieve is to make the template language and project language as independent from each other as we can. My suggestion would be to list the project languages (so the products at least change), and the template will try to use the same language (if found in the messages files), otherwise it will show one default language.
